# Generated by Django 2.1.1 on 2020-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image/')),
                ('summary', models.TextField()),
                ('detail', models.TextField()),
                ('github_link', models.CharField(blank=True, max_length=100)),
                ('submission_date', models.DateTimeField(help_text='e.g. 2020-07-16 06:35:08')),
            ],
        ),
    ]
